sonar.projectKey=Csontikka_ha-syncthing
sonar.organization=csontikka
sonar.sources=custom_components/syncthing_extended
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
