name: Release

on:
  release:
    types: [published]

jobs:
  release_zip:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Zip syncthing dir
        run: |
          cd ${{ github.workspace }}/custom_components/syncthing
          zip syncthing.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/syncthing/syncthing.zip
          asset_name: syncthing.zip
          tag: ${{ github.ref }}
          overwrite: true
